# BASIC NUMPY OPERATION

In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
